### ISSUE TITLE
Latest action version fails with Python error

### ISSUE THREAD

**Issue by rrey-aviatrix** [bridgecrewio/checkov-action#102]
```
Run bridgecrewio/checkov-action@v12.1801.0
[...]
running checkov on directory: .
checkov -d .       --output sarif         
Traceback (most recent call last):
  File "/usr/local/bin/checkov", line 9, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.8/site-packages/checkov/main.py", line [12](https://github.com/AvxSre/terraform-plans/actions/runs/3174339831/jobs/5171007781#step:4:13)2, in run
    "args": parser.format_values(sanitize=True).split('\n')
  File "/usr/local/lib/python3.8/site-packages/checkov/common/util/ext_argument_parser.py", line 43, in format_values
    if key in self.fields_to_sanitize or action.option_strings[0] in self.fields_to_sanitize:
AttributeError: 'NoneType' object has no attribute 'option_strings'
```
Also failing with `v12.1802.0`.

I had to revert to `v12.1800.0` to avoid the failure.

**Comment by gruebel** [comment]
hey @rrey-aviatrix thanks for reaching out. I tested it the latest version and had no issues. can you share the GHA config you are using?

**Comment by gruebel** [comment]
feel free to reach out again with more info or an other issue you have.
