### ISSUE TITLE
Failing version checkov-action@v12.1886.0 for framework github_actions

### ISSUE THREAD

**Issue by magnus-fors** [bridgecrewio/checkov-action#113]
Framework github_actions started to fail in version v12.1886.0 (version v12.1885.0 works fine).
```
Run bridgecrewio/checkov-action@v12.1886.0
  with:
    directory: .github/workflows
    quiet: true
    framework: github_actions
    skip_check: CKV_GHA_7
    output_format: sarif
    log_level: WARNING
    container_user: 0
  env:
    CHECKOV_RESULTS: 
         _               _              
     ___| |__   ___  ___| | _______   __
    / __| '_ \ / _ \/ __| |/ / _ \ \ / /
   | (__| | | |  __/ (__|   < (_) \ V / 
    \___|_| |_|\___|\___|_|\_\___/ \_/  
                                        
  By bridgecrew.io | version: 2.2.95 
  dockerfile scan results:
  
  Passed checks: 47, Failed checks: 0, Skipped checks: 1
```
Fails with the falling call stack:
```
running checkov on directory: .github/workflows
checkov -d .github/workflows  --skip-check CKV_GHA_7  --quiet   --output sarif        --framework github_actions  
Traceback (most recent call last):
  File "/usr/local/bin/checkov", line 9, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.8/site-packages/checkov/main.py", line 3[40](https://github.com/axteams-vms/cloud-storage/actions/runs/3549000828/jobs/5960853416#step:7:41), in run
    scan_reports = runner_registry.run(root_folder=root_folder, external_checks_dir=external_checks_dir,
  File "/usr/local/lib/python3.8/site-packages/checkov/common/runners/runner_registry.py", line 80, in run
    self.runners[0].run(root_folder, external_checks_dir=external_checks_dir, files=files,
  File "/usr/local/lib/python3.8/site-packages/checkov/github_actions/runner.py", line 109, in run
    report = super().run(root_folder=root_folder, external_checks_dir=external_checks_dir,
  File "/usr/local/lib/python3.8/site-packages/checkov/common/runners/object_runner.py", line 1[45](https://github.com/axteams-vms/cloud-storage/actions/runs/3549000828/jobs/5960853416#step:7:46), in run
    self.add_python_check_results(
  File "/usr/local/lib/python3.8/site-packages/checkov/common/runners/object_runner.py", line 190, in add_python_check_results
    resource=self.get_resource(file_path, key, check.supported_entities, start, end),  # type:ignore[arg-type]  # key is str not BaseCheck
  File "/usr/local/lib/python3.8/site-packages/checkov/github_actions/runner.py", line 96, in get_resource
    step_name = resolve_step_name(definition['jobs'][job_name], start_line, end_line)
KeyError: ''
```

**Comment by gruebel** [comment]
hey @magnus-fors thanks for reaching out. Is it possible to share the workflow file, which results in this exception? I have a hard to time to reproduce it 😓
