### ISSUE TITLE
Missing option of setting prisma-api-url / PRISMA_API_URL

### ISSUE THREAD

**Issue by andersro93** [bridgecrewio/checkov-action#151]
It seems that it is now impossible to set the prisma cloud api url. From the documentation for checkov it seems that the paramter we need is called: `--prisma-api-url`
`The Prisma Cloud API URL (see:https://prisma.pan.dev/api/cloud/api-urls). Requires –bc-api-key to be a Prisma Cloud Access Key in the following format: :: [env var: PRISMA_API_URL]`

From our runs now, we have tested with only setting the `--bc-api-key` property. It then gives us the following output:
`Error: -26 11:40:43,604 [MainThread  ] [ERROR]  Exception traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/checkov/main.py", line 397, in run
    bc_integration.setup_bridgecrew_credentials(repo_id=self.config.repo_id,
  File "/usr/local/lib/python3.11/site-packages/checkov/common/bridgecrew/platform_integration.py", line 304, in setup_bridgecrew_credentials
    self.set_s3_integration()
  File "/usr/local/lib/python3.11/site-packages/checkov/common/bridgecrew/platform_integration.py", line 317, in set_s3_integration
    repo_full_path, support_path, response = self.get_s3_role(self.repo_id)  # type: ignore
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/checkov/common/bridgecrew/platform_integration.py", line 366, in get_s3_role
    token = self.get_auth_token()
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cachetools/__init__.py", line 737, in wrapper
    v = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/checkov/common/bridgecrew/platform_integration.py", line 197, in get_auth_token
    raise ValueError("A Prisma Cloud token was set, but no Prisma Cloud API URL was set")
ValueError: A Prisma Cloud token was set, but no Prisma Cloud API URL was set
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/checkov/main.py", line 419, in run
    self.exit_run()
  File "/usr/local/lib/python3.11/site-packages/checkov/main.py", line 713, in exit_run
    exit(0) if self.config.no_fail_on_crash else exit(2)
                                                 ^^^^^^^
  File "<frozen _sitebuiltins>", line 26, in __call__
SystemExit: 2
`

**Comment by andersro93** [comment]
It seems that https://github.com/bridgecrewio/checkov-action/pull/132 is fixing this issue, could we merge that PR?

**Comment by gruebel** [comment]
hey @andersro93 thanks for reaching out.

The original creator never fixed the issues in the PR, so it is basically stale. But you also don't need the PR to make it work, just set the url via an env var

ex.
```
      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          api-key: ${{ secrets.BC_API_KEY }}
        env:
          PRISMA_API_URL: https://api.prismacloud.io 
```
