### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by MPV** [bridgecrewio/checkov-action#20]
Looks like the `master` branch of this action is broken since a couple of days/weeks back?

It ends up failing with `RecursionError: maximum recursion depth exceeded while calling a Python object`

<img width="1297" alt="Skärmavbild 2020-12-03 kl  13 56 03" src="https://user-images.githubusercontent.com/62675/101020794-4f1ee980-356f-11eb-852f-d503a3ed5dee.png">

```
>Run bridgecrewio/checkov-action@master
/usr/bin/docker run --name a8c818e812cb4c5fb46b54fd280c30ef_8371e9 --label 179394 --workdir /github/workspace --rm -e INPUT_DIRECTORY -e INPUT_QUIET -e INPUT_CHECK -e INPUT_SKIP_CHECK -e INPUT_FRAMEWORK -e INPUT_EXTERNAL_CHECKS_DIRS -e INPUT_EXTERNAL_CHECKS_REPOS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/ops/ops":"/github/workspace" 179394:a8c818e812cb4c5fb46b54fd280c30ef  "." "" "" "true" "" "" ""
running checkov on directory: .
Traceback (most recent call last):
  File "/usr/local/bin/checkov", line 5, in <module>
    run()
  File "/usr/local/lib/python3.9/site-packages/checkov/main.py", line 69, in run
    scan_reports = runner_registry.run(root_folder=root_folder, external_checks_dir=external_checks_dir,
  File "/usr/local/lib/python3.9/site-packages/checkov/common/runners/runner_registry.py", line 30, in run
    scan_report = runner.run(root_folder, external_checks_dir=external_checks_dir, files=files,
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/runner.py", line 57, in run
    self.parser.parse_directory(directory=root_folder,
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/parser.py", line 77, in parse_directory
    self._parse_directory(dir_filter=lambda d: self._check_process_dir(d))
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/parser.py", line 117, in _parse_directory
    self._internal_dir_load(sub_dir, module_loader_registry, dir_filter)
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/parser.py", line 237, in _internal_dir_load
    self._process_vars_and_locals(directory, var_value_and_file_map, module_data_retrieval)
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/parser.py", line 277, in _process_vars_and_locals
    if self._process_vars_and_locals_loop(file_data,
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/parser.py", line 411, in _process_vars_and_locals_loop
    return process_items_helper(out_definitions.items, out_definitions, outer_context, False)
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/parser.py", line 404, in process_items_helper
    if process_items_helper(lambda: enumerate(value), value, new_context, True):
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/parser.py", line 395, in process_items_helper
    if self._process_vars_and_locals_loop(value, eval_map_by_var_name, relative_file_path,
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/parser.py", line 411, in _process_vars_and_locals_loop
    return process_items_helper(out_definitions.items, out_definitions, outer_context, False)
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/parser.py", line 395, in process_items_helper
    if self._process_vars_and_locals_loop(value, eval_map_by_var_name, relative_file_path,
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/parser.py", line 411, in _process_vars_and_locals_loop
    return process_items_helper(out_definitions.items, out_definitions, outer_context, False)
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/parser.py", line 395, in process_items_helper
    if self._process_vars_and_locals_loop(value, eval_map_by_var_name, relative_file_path,
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/parser.py", line 411, in _process_vars_and_locals_loop
    return process_items_helper(out_definitions.items, out_definitions, outer_context, False)
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/parser.py", line 404, in process_items_helper
[...]
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by schosterbarak** [comment]
Hi @MPV  thank you for reporting this. i have hard time reproducing this one. 
can you share a terraform code sample here or via DM at http://slack.bridgecrew.io/ ?

**Comment by MPV** [comment]
I ended up being able to reproduce this without this action by just using `checkov`, like this:

```shell
$ checkov -d .
[...]
```

And I found the terraform code that breaks it (by commenting out different pieces until checkov started working again):

```terraform
resource "google_kms_crypto_key" "sops" {
  name       = "sops"
  key_ring   = google_kms_key_ring.sops.self_link
  depends_on = [google_kms_crypto_key.sops] # <-------------- this line specifically

  lifecycle {
    prevent_destroy = true
  }
}
```

As it turns out, that's a circular dependency.

**Comment by MPV** [comment]
So I guess we can close this issue. 😅
