### ISSUE TITLE
Custom checks seems broken since ~ 2021-05-03

### ISSUE THREAD

**Issue by aesteve** [bridgecrewio/checkov-action#40]
Hello and thank you for providing a Github action for Checkov.

We have been using `@master` action for a few months now, and it was working perfectly fine with the following setup: 

```yaml
      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./
          skip_check: CKV_GCP_49 # optional: skip a specific check_id. can be comma separated list
          quiet: true # optional: display only failed checks
          soft_fail: true # optional: do not return an error code if there are failed checks
          framework: terraform # optional: run only on a specific infrastructure {cloudformation,terraform,kubernetes,all}
          output_format: cli # optional: the output format, one of: cli, json, junitxml, github_failed_only
          download_external_modules: true # optional: download external terraform modules from public git repositories and terraform registry
          log_level: INFO # optional: set log level. Default WARNING
          external_checks_dirs: checks
```

With a few custom checks in the `checks` directory.
It has been working as expected for a few months, but it fails since 2021-05-03 **approximately**. (no changes on our repo)

It seems related to the external_checks if I'm not mistaking:

```
 2021-05-06 08:47:06,775 [MainThread  ] [INFO ]  Resultant set of frameworks (removing skipped frameworks): terraform
Traceback (most recent call last):
  File "/usr/local/bin/checkov", line 5, in <module>
    exit(run())
  File "/usr/local/lib/python3.9/site-packages/checkov/main.py", line 110, in run
    scan_reports = runner_registry.run(root_folder=root_folder, external_checks_dir=external_checks_dir,
  File "/usr/local/lib/python3.9/site-packages/checkov/common/runners/runner_registry.py", line 34, in run
    scan_report = runner.run(root_folder, external_checks_dir=external_checks_dir, files=files,
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/runner.py", line 71, in run
    self.load_external_checks(external_checks_dir)
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/runner.py", line 119, in load_external_checks
    graph_registry.load_external_checks(directory)
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/checks_infra/registry.py", line 49, in load_external_checks
    self._load_checks_from_dir(dir)
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/checks_infra/registry.py", line 29, in _load_checks_from_dir
    checks_dir_content = os.listdir(os.path.dirname(dir))
FileNotFoundError: [Errno 2] No such file or directory: ''
Cleaning up .//.external_modules directory
```

A few notes:
- we tried using `v12` for a test and the action works (unfortunately, it doesn't support `soft_fail` etc. which we are relying on)
- we tried re-running the last successful action (before ~ 2021-05-03) on the same commit (to really make sure there was no issue on our side) and it does fail with the same error as above.

Please let us know if you need more information, or if you need us to run more experiments.
We de-activated the action for now since it's breaking the build, if you have some easy-workaround waiting for a fix, it'd be really nice, but we can live a few weeks without one.

Thanks again for your work, do not hesitate.

**Comment by nimrodkor** [comment]
Good catch. Will take a look now

**Comment by nimrodkor** [comment]
Hey @aesteve , can you try again now, against master?

**Comment by aesteve** [comment]
Can confirm it's working again! Thanks!
