### ISSUE TITLE
Checkov Action Crashes

### ISSUE THREAD

**Issue by ArneRiemann4711** [bridgecrewio/checkov-action#53]
Howdy,

```
checkov -d terraform/demo  --skip-check CKV_AWS_65,CKV_AWS_51,CKV_AWS_23,CKV_AWS_85,CKV_AWS_40,CKV_AWS_52,CKV_AWS_21,CKV_AWS_18,CKV2_AWS_5 --quiet        --framework terraform
Traceback (most recent call last):
  File "/usr/local/bin/checkov", line 8, in <module>
    exit(run())
  File "/usr/local/lib/python3.7/site-packages/checkov/main.py", line 175, in run
    files=file, guidelines=guidelines)
  File "/usr/local/lib/python3.7/site-packages/checkov/common/runners/runner_registry.py", line 54, in run
    collect_skip_comments=collect_skip_comments,
  File "/usr/local/lib/python3.7/site-packages/checkov/terraform/runner.py", line 77, in run
    vars_files=runner_filter.var_files)
  File "/usr/local/lib/python3.7/site-packages/checkov/terraform/graph_manager.py", line 18, in build_graph_from_source_directory
    self.parser.parse_hcl_module(source_dir, self.source, download_external_modules, parsing_errors, excluded_paths=excluded_paths, vars_files=vars_files)
  File "/usr/local/lib/python3.7/site-packages/checkov/terraform/parser.py", line 455, in parse_hcl_module
    vars_files=vars_files)
  File "/usr/local/lib/python3.7/site-packages/checkov/terraform/parser.py", line 101, in parse_directory
    self._parse_directory(dir_filter=lambda d: self._check_process_dir(d), vars_files=vars_files)
  File "/usr/local/lib/python3.7/site-packages/checkov/terraform/parser.py", line 141, in _parse_directory
    _filter_ignored_paths(sub_dir, d_names, self.excluded_paths)
  File "/usr/local/lib/python3.7/site-packages/checkov/terraform/parser.py", line 42, in _filter_ignored_paths
    filter_ignored_paths(root, paths, excluded_paths)
  File "/usr/local/lib/python3.7/site-packages/checkov/common/runners/base_runner.py", line 104, in filter_ignored_paths
    names.remove(path)
ValueError: list.remove(x): x not in list
```

Any ideas?

Tried:

- Rerunning Actions

**Comment by schosterbarak** [comment]
Thanks for reporting @ArneRiemann4711  i just tried to apply a fix. can you let me know if that is still happening for you?

**Comment by ArneRiemann4711** [comment]
Works, thanks!
