### ISSUE TITLE
checkov-action check on plan file (json) not working suppression.py NoneType

### ISSUE THREAD

**Issue by zamirTo1** [bridgecrewio/checkov-action#98]
Hey,
Running on ubuntu-latest with python 3.9.13 x64
getting this error:
````
Process ForkProcess-7:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/checkov/common/parallelizer/parallel_runner.py", line 37, in func_wrapper
    result = original_func(item)
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/checkov/common/runners/runner_registry.py", line 84, in _parallel_run
    return runner.run(
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/checkov/github/runner.py", line 36, in run
    report = super().run(root_folder=self.github.github_conf_dir_path, external_checks_dir=external_checks_dir,
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/checkov/common/runners/object_runner.py", line 105, in run
    skipped_checks = collect_suppressions_for_context(definitions_raw[file_path])
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/checkov/common/util/suppression.py", line 36, in collect_suppressions_for_context
    for line_number, line_text in code_lines:
TypeError: 'NoneType' object is not iterable
Process ForkProcess-8:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/multiprocessing/process.py", line [31](https://github.com/XXXXX-XXXXX/XXXXX/actions/runs/3092340944/jobs/5003496315#step:9:32)5, in _bootstrap
    self.run()
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/checkov/common/parallelizer/parallel_runner.py", line 37, in func_wrapper
    result = original_func(item)
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/checkov/common/runners/runner_registry.py", line 84, in _parallel_run
    return runner.run(
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/checkov/gitlab/runner.py", line [35](https://github.com/XXXXX/XXXXX/actions/runs/3092340944/jobs/5003496315#step:9:36), in run
    report = super().run(root_folder=self.gitlab.gitlab_conf_dir_path, external_checks_dir=external_checks_dir,
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/checkov/common/runners/object_runner.py", line 105, in run
    skipped_checks = collect_suppressions_for_context(definitions_raw[file_path])
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/checkov/common/util/suppression.py", line 36, in collect_suppressions_for_context
    for line_number, line_text in code_lines:
TypeError: 'NoneType' object is not iterable
Process ForkProcess-9:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/checkov/common/parallelizer/parallel_runner.py", line 37, in func_wrapper
    result = original_func(item)
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/checkov/common/runners/runner_registry.py", line 84, in _parallel_run
    return runner.run(
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/checkov/bitbucket/runner.py", line [36](https://github.com/XXXXX/XXXXX/actions/runs/3092340944/jobs/5003496315#step:9:37), in run
    report = super().run(root_folder=self.bitbucket.bitbucket_conf_dir_path, external_checks_dir=external_checks_dir,
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/checkov/common/runners/object_runner.py", line 105, in run
    skipped_checks = collect_suppressions_for_context(definitions_raw[file_path])
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/checkov/common/util/suppression.py", line 36, in collect_suppressions_for_context
    for line_number, line_text in code_lines:
TypeError: 'NoneType' object is not iterable

       _               _              
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V / 
  \___|_| |_|\___|\___|_|\_\___/ \_/  
                                      
By bridgecrew.io | version: 2.1.219 
terraform_plan scan results:

Passed checks: 0, Failed checks: 0, Skipped checks: 0, Parsing errors: 1

Error parsing file /home/runner/work/XXXXXX/XXXXXX/XXXXXX/XXXXXX/test/plan.jsonֿ
```

Wrote output in SARIF format to the file 'results.sarif'`

Please assist.

**Comment by Saarett** [comment]
Hey @zamirTo1 , can you please share an example file so we can reproduce it?

**Comment by zamirTo1** [comment]
TF file:
```
resource "aws_s3_bucket" "b" {
  bucket = "my-tf-test-bucket"

  tags = {
    Name        = "My bucket"
    Environment = "Dev"
  }
}

resource "aws_s3_bucket_acl" "example" {
  bucket = aws_s3_bucket.b.id
  acl    = "public-read"
}
```

TF plan json file:
```
{"format_version":"1.0","terraform_version":"1.1.0","variables":{"region":{"value":"us-west-2"}},"planned_values":{"root_module":{"resources":[{"address":"aws_s3_bucket.b","mode":"managed","type":"aws_s3_bucket","name":"b","provider_name":"registry.terraform.io/hashicorp/aws","schema_version":0,"values":{"acl":"private","bucket":"my-tf-test-bucket","bucket_prefix":null,"cors_rule":[],"force_destroy":false,"grant":[],"lifecycle_rule":[],"logging":[],"policy":null,"replication_configuration":[],"server_side_encryption_configuration":[],"tags":{"Environment":"Dev","Name":"My bucket"},"tags_all":{"Environment":"Dev","Name":"My bucket"},"website":[]},"sensitive_values":{"cors_rule":[],"grant":[],"lifecycle_rule":[],"logging":[],"object_lock_configuration":[],"replication_configuration":[],"server_side_encryption_configuration":[],"tags":{},"tags_all":{},"versioning":[],"website":[]}},{"address":"aws_s3_bucket_acl.example","mode":"managed","type":"aws_s3_bucket_acl","name":"example","provider_name":"registry.terraform.io/hashicorp/aws","schema_version":0,"values":{"acl":"public-read","expected_bucket_owner":null},"sensitive_values":{"access_control_policy":[]}}]}},"resource_changes":[{"address":"aws_s3_bucket.b","mode":"managed","type":"aws_s3_bucket","name":"b","provider_name":"registry.terraform.io/hashicorp/aws","change":{"actions":["create"],"before":null,"after":{"acl":"private","bucket":"my-tf-test-bucket","bucket_prefix":null,"cors_rule":[],"force_destroy":false,"grant":[],"lifecycle_rule":[],"logging":[],"policy":null,"replication_configuration":[],"server_side_encryption_configuration":[],"tags":{"Environment":"Dev","Name":"My bucket"},"tags_all":{"Environment":"Dev","Name":"My bucket"},"website":[]},"after_unknown":{"acceleration_status":true,"arn":true,"bucket_domain_name":true,"bucket_regional_domain_name":true,"cors_rule":[],"grant":[],"hosted_zone_id":true,"id":true,"lifecycle_rule":[],"logging":[],"object_lock_configuration":true,"object_lock_enabled":true,"region":true,"replication_configuration":[],"request_payer":true,"server_side_encryption_configuration":[],"tags":{},"tags_all":{},"versioning":true,"website":[],"website_domain":true,"website_endpoint":true},"before_sensitive":false,"after_sensitive":{"cors_rule":[],"grant":[],"lifecycle_rule":[],"logging":[],"object_lock_configuration":[],"replication_configuration":[],"server_side_encryption_configuration":[],"tags":{},"tags_all":{},"versioning":[],"website":[]}}},{"address":"aws_s3_bucket_acl.example","mode":"managed","type":"aws_s3_bucket_acl","name":"example","provider_name":"registry.terraform.io/hashicorp/aws","change":{"actions":["create"],"before":null,"after":{"acl":"public-read","expected_bucket_owner":null},"after_unknown":{"access_control_policy":true,"bucket":true,"id":true},"before_sensitive":false,"after_sensitive":{"access_control_policy":[]}}}],"configuration":{"provider_config":{"aws":{"name":"aws","version_constraint":"\u003c 4.0.0","expressions":{"region":{"constant_value":"us-west-2"}}},"aws.east":{"name":"aws","alias":"east","version_constraint":"\u003c 4.0.0","expressions":{"assume_role":[{"role_arn":{"references":["var.ENVIRONMENT"]},"session_name":{"references":["var.SESSION_NAME"]}}],"region":{"constant_value":"us-east-1"}}}},"root_module":{"resources":[{"address":"aws_s3_bucket.b","mode":"managed","type":"aws_s3_bucket","name":"b","provider_config_key":"aws","expressions":{"bucket":{"constant_value":"my-tf-test-bucket"},"tags":{"constant_value":{"Environment":"Dev","Name":"My bucket"}}},"schema_version":0},{"address":"aws_s3_bucket_acl.example","mode":"managed","type":"aws_s3_bucket_acl","name":"example","provider_config_key":"aws","expressions":{"acl":{"constant_value":"public-read"},"bucket":{"references":["aws_s3_bucket.b.id","aws_s3_bucket.b"]}},"schema_version":0}],"variables":{"region":{"default":"us-west-2"}}}}}
```

action:
```
- name: checkov scan
      id: checkov
      uses: bridgecrewio/checkov-action@master
      with:
          file: ${{ matrix.folders }}plan.json
          quiet: true
          framework: terraform_plan
```
